Traceback (most recent call last):
  File "/home/gilberthan/anaconda3/envs/readthedoct/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/gilberthan/anaconda3/envs/readthedoct/lib/python3.10/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gilberthan/.local/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 160, in wrapped
    return loop.run_until_complete(inner)
  File "/home/gilberthan/anaconda3/envs/readthedoct/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/gilberthan/anaconda3/envs/readthedoct/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/gilberthan/anaconda3/envs/readthedoct/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/gilberthan/anaconda3/envs/readthedoct/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
adata = sc.read("../../processed_data/integrated_data/20241021_filtered_log_count.h5ad")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [0;32mIn[5], line 1[0m
[0;32m----> 1[0m adata [38;5;241m=[39m [43msc[49m[38;5;241;43m.[39;49m[43mread[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m../../processed_data/integrated_data/20241021_filtered_log_count.h5ad[39;49m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m~/anaconda3/envs/py311/lib/python3.11/site-packages/legacy_api_wrap/__init__.py:80[0m, in [0;36mlegacy_api.<locals>.wrapper.<locals>.fn_compatible[0;34m(*args_all, **kw)[0m
[1;32m     77[0m [38;5;129m@wraps[39m(fn)
[1;32m     78[0m [38;5;28;01mdef[39;00m [38;5;21mfn_compatible[39m([38;5;241m*[39margs_all: P[38;5;241m.[39margs, [38;5;241m*[39m[38;5;241m*[39mkw: P[38;5;241m.[39mkwargs) [38;5;241m-[39m[38;5;241m>[39m R:
[1;32m     79[0m     [38;5;28;01mif[39;00m [38;5;28mlen[39m(args_all) [38;5;241m<[39m[38;5;241m=[39m n_positional:
[0;32m---> 80[0m         [38;5;28;01mreturn[39;00m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs_all[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkw[49m[43m)[49m
[1;32m     82[0m     args_pos: P[38;5;241m.[39margs
[1;32m     83[0m     args_pos, args_rest [38;5;241m=[39m args_all[:n_positional], args_all[n_positional:]

File [0;32m~/anaconda3/envs/py311/lib/python3.11/site-packages/scanpy/readwrite.py:124[0m, in [0;36mread[0;34m(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)[0m
[1;32m    122[0m filename [38;5;241m=[39m Path(filename)  [38;5;66;03m# allow passing strings[39;00m
[1;32m    123[0m [38;5;28;01mif[39;00m is_valid_filename(filename):
[0;32m--> 124[0m     [38;5;28;01mreturn[39;00m [43m_read[49m[43m([49m
[1;32m    125[0m [43m        [49m[43mfilename[49m[43m,[49m
[1;32m    126[0m [43m        [49m[43mbacked[49m[38;5;241;43m=[39;49m[43mbacked[49m[43m,[49m
[1;32m    127[0m [43m        [49m[43msheet[49m[38;5;241;43m=[39;49m[43msheet[49m[43m,[49m
[1;32m    128[0m [43m        [49m[43mext[49m[38;5;241;43m=[39;49m[43mext[49m[43m,[49m
[1;32m    129[0m [43m        [49m[43mdelimiter[49m[38;5;241;43m=[39;49m[43mdelimiter[49m[43m,[49m
[1;32m    130[0m [43m        [49m[43mfirst_column_names[49m[38;5;241;43m=[39;49m[43mfirst_column_names[49m[43m,[49m
[1;32m    131[0m [43m        [49m[43mbackup_url[49m[38;5;241;43m=[39;49m[43mbackup_url[49m[43m,[49m
[1;32m    132[0m [43m        [49m[43mcache[49m[38;5;241;43m=[39;49m[43mcache[49m[43m,[49m
[1;32m    133[0m [43m        [49m[43mcache_compression[49m[38;5;241;43m=[39;49m[43mcache_compression[49m[43m,[49m
[1;32m    134[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m,[49m
[1;32m    135[0m [43m    [49m[43m)[49m
[1;32m    136[0m [38;5;66;03m# generate filename and read to dict[39;00m
[1;32m    137[0m filekey [38;5;241m=[39m [38;5;28mstr[39m(filename)

File [0;32m~/anaconda3/envs/py311/lib/python3.11/site-packages/scanpy/readwrite.py:759[0m, in [0;36m_read[0;34m(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, suppress_cache_warning, **kwargs)[0m
[1;32m    757[0m [38;5;28;01mif[39;00m ext [38;5;129;01min[39;00m {[38;5;124m"[39m[38;5;124mh5[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mh5ad[39m[38;5;124m"[39m}:
[1;32m    758[0m     [38;5;28;01mif[39;00m sheet [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m--> 759[0m         [38;5;28;01mreturn[39;00m [43mread_h5ad[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[43mbacked[49m[38;5;241;43m=[39;49m[43mbacked[49m[43m)[49m
[1;32m    760[0m     [38;5;28;01melse[39;00m:
[1;32m    761[0m         logg[38;5;241m.[39mdebug([38;5;124mf[39m[38;5;124m"[39m[38;5;124mreading sheet [39m[38;5;132;01m{[39;00msheet[38;5;132;01m}[39;00m[38;5;124m from file [39m[38;5;132;01m{[39;00mfilename[38;5;132;01m}[39;00m[38;5;124m"[39m)

File [0;32m~/anaconda3/envs/py311/lib/python3.11/site-packages/anndata/_io/h5ad.py:237[0m, in [0;36mread_h5ad[0;34m(filename, backed, as_sparse, as_sparse_fmt, chunk_size)[0m
[1;32m    229[0m         [38;5;28;01mraise[39;00m [38;5;167;01mNotImplementedError[39;00m(
[1;32m    230[0m             [38;5;124m"[39m[38;5;124mCurrently only `X` and `raw/X` can be read as sparse.[39m[38;5;124m"[39m
[1;32m    231[0m         )
[1;32m    233[0m rdasp [38;5;241m=[39m partial(
[1;32m    234[0m     read_dense_as_sparse, sparse_format[38;5;241m=[39mas_sparse_fmt, axis_chunk[38;5;241m=[39mchunk_size
[1;32m    235[0m )
[0;32m--> 237[0m [38;5;28;01mwith[39;00m [43mh5py[49m[38;5;241;43m.[39;49m[43mFile[49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;124;43mr[39;49m[38;5;124;43m"[39;49m[43m)[49m [38;5;28;01mas[39;00m f:
[1;32m    239[0m     [38;5;28;01mdef[39;00m [38;5;21mcallback[39m(func, elem_name: [38;5;28mstr[39m, elem, iospec):
[1;32m    240[0m         [38;5;28;01mif[39;00m iospec[38;5;241m.[39mencoding_type [38;5;241m==[39m [38;5;124m"[39m[38;5;124manndata[39m[38;5;124m"[39m [38;5;129;01mor[39;00m elem_name[38;5;241m.[39mendswith([38;5;124m"[39m[38;5;124m/[39m[38;5;124m"[39m):

File [0;32m~/anaconda3/envs/py311/lib/python3.11/site-packages/h5py/_hl/files.py:562[0m, in [0;36mFile.__init__[0;34m(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, meta_block_size, **kwds)[0m
[1;32m    553[0m     fapl [38;5;241m=[39m make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
[1;32m    554[0m                      locking, page_buf_size, min_meta_keep, min_raw_keep,
[1;32m    555[0m                      alignment_threshold[38;5;241m=[39malignment_threshold,
[1;32m    556[0m                      alignment_interval[38;5;241m=[39malignment_interval,
[1;32m    557[0m                      meta_block_size[38;5;241m=[39mmeta_block_size,
[1;32m    558[0m                      [38;5;241m*[39m[38;5;241m*[39mkwds)
[1;32m    559[0m     fcpl [38;5;241m=[39m make_fcpl(track_order[38;5;241m=[39mtrack_order, fs_strategy[38;5;241m=[39mfs_strategy,
[1;32m    560[0m                      fs_persist[38;5;241m=[39mfs_persist, fs_threshold[38;5;241m=[39mfs_threshold,
[1;32m    561[0m                      fs_page_size[38;5;241m=[39mfs_page_size)
[0;32m--> 562[0m     fid [38;5;241m=[39m [43mmake_fid[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mmode[49m[43m,[49m[43m [49m[43muserblock_size[49m[43m,[49m[43m [49m[43mfapl[49m[43m,[49m[43m [49m[43mfcpl[49m[43m,[49m[43m [49m[43mswmr[49m[38;5;241;43m=[39;49m[43mswmr[49m[43m)[49m
[1;32m    564[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(libver, [38;5;28mtuple[39m):
[1;32m    565[0m     [38;5;28mself[39m[38;5;241m.[39m_libver [38;5;241m=[39m libver

File [0;32m~/anaconda3/envs/py311/lib/python3.11/site-packages/h5py/_hl/files.py:235[0m, in [0;36mmake_fid[0;34m(name, mode, userblock_size, fapl, fcpl, swmr)[0m
[1;32m    233[0m     [38;5;28;01mif[39;00m swmr [38;5;129;01mand[39;00m swmr_support:
[1;32m    234[0m         flags [38;5;241m|[39m[38;5;241m=[39m h5f[38;5;241m.[39mACC_SWMR_READ
[0;32m--> 235[0m     fid [38;5;241m=[39m [43mh5f[49m[38;5;241;43m.[39;49m[43mopen[49m[43m([49m[43mname[49m[43m,[49m[43m [49m[43mflags[49m[43m,[49m[43m [49m[43mfapl[49m[38;5;241;43m=[39;49m[43mfapl[49m[43m)[49m
[1;32m    236[0m [38;5;28;01melif[39;00m mode [38;5;241m==[39m [38;5;124m'[39m[38;5;124mr+[39m[38;5;124m'[39m:
[1;32m    237[0m     fid [38;5;241m=[39m h5f[38;5;241m.[39mopen(name, h5f[38;5;241m.[39mACC_RDWR, fapl[38;5;241m=[39mfapl)

File [0;32mh5py/_objects.pyx:54[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/_objects.pyx:55[0m, in [0;36mh5py._objects.with_phil.wrapper[0;34m()[0m

File [0;32mh5py/h5f.pyx:102[0m, in [0;36mh5py.h5f.open[0;34m()[0m

[0;31mFileNotFoundError[0m: [Errno 2] Unable to synchronously open file (unable to open file: name = '../../processed_data/integrated_data/20241021_filtered_log_count.h5ad', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

